place = ["Bali", "Paris", "Bora Bora", "Siargao", "Tokyo"]
print(place)
print(" ")
print(sorted(place))
print(place)
print(" ")
print(sorted(place, reverse=True))
print(place)
print(" ")
place.reverse()
print(place)
place.reverse()
print(place)
print(" ")
place.sort()
print(place)
place.sort(reverse=True)
print(place)