# -*- coding: utf-8 -*-
"""For Loop Class Activity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tVjjwkEf174DNb1o6i69dhOwBVFjolu
"""

Apple = ["A", "P", "P", "L", "E"]
print("The following lines will print each letters of Apple:")
for letters in Apple:
    print(letters)

Banana = ["B", "A", "N", "A", "N", "A"]
print("\nThe following lines will print each letters of Banana:")
for letters in Banana:
    print(letters)

Car = ["C", "A", "R"]
print("\nThe following lines will print each letters of Car:")
for letters in Car:
    print(letters)

Dolphin = ["D", "O", "L", "P", "H", "I", "N"]
print("\nThe following lines will print each letters of Dolphin:")
for letters in Dolphin:
    print(letters)